# We use a volume for docker cache,
# we can keep the downloaded packages to speed up image rebuilds.
Binary::apt::APT::Keep-Downloaded-Packages "true";

# For non-interactive installs
APT::Get::Assume-Yes "true";

# Good to know what version of the packages we're installing
APT::Get::Show-Versions "true";

# Keep layers stable, for reproducibility
APT::Get::Upgrade "false";

# Avoids installing unneeded packages
APT::Install-Recommends "false";
APT::Install-Suggests "false";
APT::Get::AutomaticRemove "true";
