name: gsplat
channels:
  - pytorch3d
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - setuptools==69.5.1
  - python=3.10
  - pip
  - plyfile
  - tqdm
  - tyro
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=12.1
  - typing_extensions
  - numpy=1.26.4
  - scikit-learn
  - pip:
    - viser
    - tensorboard
    - pyyaml
    - open3d==0.18.0
    - tqdm 
    - pillow
    - plyfile