[pytest]
testpaths = tests
pythonpath = .
filterwarnings =
    ignore::DeprecationWarning:_pytest
    ignore::SyntaxWarning:nerfacc
env =
    VERBOSE=1
    BUILD_CAMERA_WRAPPERS=1
    NUM_CHANNELS=1,3,4,8,24,32,128

