# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""CPU-only tests for the PLY ``SplatRenderMode`` header comment.

These verify that :func:`gsplat.exporter.export_splats` records the
antialiased (mip-splatting) rasterization mode as a ``SplatRenderMode`` PLY
header comment, and that :func:`gsplat.exporter.load_ply_to_splats` reads it
back. No CUDA is required.
"""

from __future__ import annotations

import torch

from gsplat.exporter import (
    _render_mode_comment_line,
    export_splats,
    load_ply_to_splats,
    parse_render_mode_comment,
    splat2ply_bytes,
    splat2ply_bytes_compressed,
)


def _make_splats(n: int = 16, k: int = 4):
    """Return a small, valid random splat model on CPU."""
    torch.manual_seed(0)
    means = torch.randn(n, 3)
    scales = torch.randn(n, 3)
    quats = torch.randn(n, 4)
    # Keep opacities well above the 1/255 compressed-export threshold.
    opacities = torch.full((n,), 5.0)
    sh0 = torch.randn(n, 1, 3)
    shN = torch.randn(n, k, 3)
    return means, scales, quats, opacities, sh0, shN


def _header(data: bytes) -> str:
    """Return the ASCII PLY header (up to and including end_header)."""
    end = data.index(b"end_header")
    return data[:end].decode("ascii")


def test_render_mode_comment_line():
    assert _render_mode_comment_line(True) == b"comment SplatRenderMode: mip\n"
    assert _render_mode_comment_line(False) == b"comment SplatRenderMode: default\n"
    assert _render_mode_comment_line(None) == b""


def test_parse_render_mode_comment():
    assert parse_render_mode_comment(["SplatRenderMode: mip"]) == "antialiased"
    assert parse_render_mode_comment(["SplatRenderMode: default"]) == "classic"
    # Case-insensitive and tolerant of surrounding whitespace.
    assert parse_render_mode_comment(["  splatrendermode:   MIP "]) == "antialiased"
    # Unrelated / absent comments -> None.
    assert parse_render_mode_comment(["Generated by X"]) is None
    assert parse_render_mode_comment([]) is None
    assert parse_render_mode_comment(None) is None
    # Last matching comment wins.
    assert (
        parse_render_mode_comment(
            ["SplatRenderMode: default", "SplatRenderMode: mip"]
        )
        == "antialiased"
    )


def test_splat2ply_bytes_writes_comment():
    means, scales, quats, opacities, sh0, shN = _make_splats()
    sh0f = sh0.squeeze(1)
    shNf = shN.permute(0, 2, 1).reshape(means.shape[0], -1)

    assert "comment SplatRenderMode: mip" in _header(
        splat2ply_bytes(means, scales, quats, opacities, sh0f, shNf, antialiased=True)
    )
    assert "comment SplatRenderMode: default" in _header(
        splat2ply_bytes(means, scales, quats, opacities, sh0f, shNf, antialiased=False)
    )
    # Default (None) preserves the previous behavior: no such comment.
    assert "SplatRenderMode" not in _header(
        splat2ply_bytes(means, scales, quats, opacities, sh0f, shNf)
    )


def test_splat2ply_bytes_compressed_writes_comment():
    means, scales, quats, opacities, sh0, shN = _make_splats()
    sh0f = sh0.squeeze(1)
    shNf = shN.permute(0, 2, 1).reshape(means.shape[0], -1)

    assert "comment SplatRenderMode: mip" in _header(
        splat2ply_bytes_compressed(
            means, scales, quats, opacities, sh0f, shNf, antialiased=True
        )
    )
    assert "comment SplatRenderMode: default" in _header(
        splat2ply_bytes_compressed(
            means, scales, quats, opacities, sh0f, shNf, antialiased=False
        )
    )


def test_export_splats_ply_roundtrip(tmp_path):
    means, scales, quats, opacities, sh0, shN = _make_splats()

    for antialiased, expected in [(True, "antialiased"), (False, "classic")]:
        path = tmp_path / f"splat_{antialiased}.ply"
        export_splats(
            means=means,
            scales=scales,
            quats=quats,
            opacities=opacities,
            sh0=sh0,
            shN=shN,
            format="ply",
            save_to=str(path),
            antialiased=antialiased,
        )
        loaded = load_ply_to_splats(str(path))
        assert loaded["rasterize_mode"] == expected


def test_export_splats_ply_no_mode_by_default(tmp_path):
    means, scales, quats, opacities, sh0, shN = _make_splats()
    path = tmp_path / "splat_none.ply"
    export_splats(
        means=means,
        scales=scales,
        quats=quats,
        opacities=opacities,
        sh0=sh0,
        shN=shN,
        format="ply",
        save_to=str(path),
    )
    loaded = load_ply_to_splats(str(path))
    assert loaded["rasterize_mode"] is None
