// Copyright (C) 2026 Advanced Micro Devices, Inc. All Rights Reserved.
// !!! This is a file automatically generated by hipify!!!
// SPDX-License-Identifier: Apache-2.0
//
// HIP-safe shim for `<cooperative_groups/reduce.h>`. ROCm 7.x provides the
// core `<hip/hip_cooperative_groups.h>` API but does NOT ship the separate
// `cooperative_groups/reduce.h` header (or `cg::reduce` / `cg::plus<T>` /
// `cg::greater<T>` template entry points) that the gsplat kernels depend on.
//
// This drop-in re-implements the small surface gsplat actually uses with a
// `__shfl_*` shuffle reduction. It is portable across wave32 (RDNA) and
// wave64 (CDNA) — the loop reads `warpSize` at compile time on AMD targets,
// so the same code generates a 5-step reduction on RDNA and a 6-step
// reduction on CDNA without per-arch ifdefs.
//
// Reference: cuda_to_hip_porting_lessons.md §4.4 / §12 — drop-in shim for
// `cooperative_groups/reduce.h`.
#pragma once

#if defined(__HIPCC__) || defined(__HIP_PLATFORM_AMD__) || \
    defined(__HIP_PLATFORM_HCC__) || defined(USE_ROCM)

#include <hip/hip_cooperative_groups.h>
#include <hip/hip_runtime.h>

namespace cooperative_groups {

template <typename T>
struct plus {
    __device__ __host__ T operator()(T a, T b) const { return a + b; }
};

template <typename T>
struct greater {
    __device__ __host__ T operator()(T a, T b) const { return a > b ? a : b; }
};

template <typename T>
struct less {
    __device__ __host__ T operator()(T a, T b) const { return a < b ? a : b; }
};

// Warp-wide reduce. Mirrors cg::reduce(warp_tile, val, Op{}) — gsplat only
// instantiates this for tiled_partition<warpSize> tiles, so we shuffle
// across the full wavefront. Wave-portable: relies on the warpSize device
// builtin instead of hard-coding 32 (RDNA) or 64 (CDNA).
template <typename WarpTile, typename T, typename Op>
__device__ __forceinline__ T reduce(const WarpTile &/*tile*/, T val, Op op) {
    #pragma unroll
    for (int offset = warpSize / 2; offset > 0; offset >>= 1) {
        T other = __shfl_down(val, offset);
        val = op(val, other);
    }
    return val;
}

// Degenerate `cg::labeled_partition` for ROCm (lesson cuda_to_hip_porting
// §4.5). The CUDA/CCCL `labeled_partition(warp, label)` groups threads of
// the warp by label value and lets the leader thread of each group
// accumulate the within-group sum. ROCm provides no equivalent.
//
// We return a "single-lane group" — every thread is its own group of one.
// `thread_rank()` is always 0, so every thread becomes the leader, and the
// `reduce` overload below is a no-op pass-through. The downstream code path
// in gsplat's projection backward kernels then performs `gpuAtomicAdd`
// per-thread instead of one-add-per-label-group. The destination receives
// the same total (sum of every contribution) — just via more atomics. This
// is correct, conservative, and the trade-off the lesson recommends.
struct labeled_partition_lane_t {
    __device__ __host__ unsigned int thread_rank() const { return 0u; }
    __device__ __host__ unsigned int size() const { return 1u; }
};

template <typename WarpTile, typename Label>
__device__ __forceinline__ labeled_partition_lane_t
labeled_partition(const WarpTile &/*warp*/, Label /*label*/) {
    return labeled_partition_lane_t{};
}

// reduce overload for the degenerate group: no shuffle, just return val.
template <typename T, typename Op>
__device__ __forceinline__ T reduce(const labeled_partition_lane_t &, T val, Op /*op*/) {
    return val;
}

} // namespace cooperative_groups

#endif // __HIPCC__
