// Copyright (C) 2026 Advanced Micro Devices, Inc. All Rights Reserved.
// !!! This is a file automatically generated by hipify!!!
#include "hip/hip_runtime.h"
/*
 * SPDX-FileCopyrightText: Copyright 2025 the Regents of the University of California, Nerfstudio Team and contributors. All rights reserved.
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include <algorithm>
#include <cstdint>

// GLM 0.9.9.8 (bundled at gsplat/third_party/glm/) was patched by gsplat to
// recognize amdclang++/hipcc — see gsplat/third_party/glm/glm/simd/platform.h
// for the `defined(__CUDACC__) || defined(__HIPCC__)` clause that sets
// GLM_COMPILER to GLM_COMPILER_CUDA80 on the HIP path. That makes
// GLM_CUDA_FUNC_DEF expand to `__device__ __host__` so every GLM math call
// (glm::quat_cast / length / cross / slerp / rotate / mat3_cast /
// outerProduct / inverse / dot / transpose) is callable from __device__
// functions. Without this the GLM-heavy projection kernels do not build.

// GLM gtx headers (e.g. matrix_operation, quaternion) require this to opt
// in to the experimental APIs gsplat depends on (slerp, mat3_cast,
// outerProduct on quat-derived types, etc.). Define it here so every TU
// that pulls in Common.h picks it up before any gtx/* include.
#ifndef GLM_ENABLE_EXPERIMENTAL
#  define GLM_ENABLE_EXPERIMENTAL
#endif

// HIP: rewire hipcub:: -> hipcub:: for the DoubleBuffer / DeviceRadixSort
// symbols. PyTorch hipify rewrites only some hipcub:: symbols and leaves
// others (DoubleBuffer) un-rewritten on amdclang++. The alias makes every
// hipcub:: symbol resolve to the hipcub equivalent on the HIP path.
#if defined(__HIPCC__)
#  include <hipcub/hipcub.hpp>
namespace cub = hipcub;
#endif

#include <glm/gtc/type_ptr.hpp>
#include <glm/glm.hpp>
// Pull in the GLM extensions gsplat actually uses (quaternion ↔ matrix
// conversions, slerp, length/norm, matrix transforms, outerProduct).
// On amdclang++ these aren't auto-included by <glm/glm.hpp>, and the headers
// that previously pulled them in (Cameras.cuh) only see them after Common.h
// has already cached <glm/glm.hpp> behind its include guards.
#include <glm/gtc/quaternion.hpp>
#include <glm/gtc/matrix_inverse.hpp>
#include <glm/gtx/matrix_operation.hpp>
#include <glm/gtx/quaternion.hpp>
#include <glm/gtx/norm.hpp>
#include <glm/gtx/transform.hpp>

// HIP-safe optional substitute (lesson cuda-translation-b51).
//
// AMD-native ROCm output: no CUDA fallback. libcu++'s `cuda::std::optional`
// is unusable on HIP kernels (libstdc++'s __throw_bad_optional_access is
// __host__-only); ROCm provides no equivalent. We ship a tiny
// trivially-copyable POD-style replacement and use it unconditionally.
namespace gsplat {

struct nullopt_t { explicit constexpr nullopt_t(int) {} };
inline constexpr nullopt_t nullopt{0};

// Trivially-copyable optional<T> with no exception path. T MUST be a POD-like
// trivially copyable / destructible type — true for the device-parameter
// structs gsplat passes through this template. Trivial copyability is
// required so the type can be passed by value to a __global__ kernel; the
// special members are intentionally =default and we store the payload as a
// raw byte buffer so the compiler doesn't synthesize a non-trivial copy.
template <typename T>
struct optional {
    alignas(T) unsigned char storage_[sizeof(T)];
    bool has_value_;

    optional() = default;
    optional(const optional &) = default;
    optional &operator=(const optional &) = default;
    ~optional() = default;

    __host__ __device__ optional(nullopt_t) noexcept : storage_{}, has_value_(false) {}
    __host__ __device__ optional(const T &v) : has_value_(true) {
        // Bitwise copy is safe because T is trivially copyable.
        __builtin_memcpy(storage_, &v, sizeof(T));
    }
    __host__ __device__ optional &operator=(nullopt_t) noexcept {
        has_value_ = false; return *this;
    }
    __host__ __device__ optional &operator=(const T &v) {
        __builtin_memcpy(storage_, &v, sizeof(T));
        has_value_ = true;
        return *this;
    }

    __host__ __device__ bool has_value() const noexcept { return has_value_; }
    __host__ __device__ explicit operator bool() const noexcept { return has_value_; }

    __host__ __device__ T &value() &
        { return *reinterpret_cast<T *>(storage_); }
    __host__ __device__ const T &value() const &
        { return *reinterpret_cast<const T *>(storage_); }
    __host__ __device__ T &operator*() &
        { return *reinterpret_cast<T *>(storage_); }
    __host__ __device__ const T &operator*() const &
        { return *reinterpret_cast<const T *>(storage_); }
    __host__ __device__ T *operator->()
        { return reinterpret_cast<T *>(storage_); }
    __host__ __device__ const T *operator->() const
        { return reinterpret_cast<const T *>(storage_); }
};


//
// Some Macros.
//
#define CHECK_CUDA(x) TORCH_CHECK(x.is_cuda(), #x " must be a CUDA tensor")
#define CHECK_CONTIGUOUS(x)                                                    \
    TORCH_CHECK(x.is_contiguous(), #x " must be contiguous")
#define CHECK_INPUT(x)                                                         \
    CHECK_CUDA(x);                                                             \
    CHECK_CONTIGUOUS(x)
#define DEVICE_GUARD(_ten)                                                     \
    const at::cuda::OptionalCUDAGuard device_guard(device_of(_ten));

// https://github.com/pytorch/pytorch/blob/233305a852e1cd7f319b15b5137074c9eac455f6/aten/src/ATen/cuda/cub.cuh#L38-L46
// handle the temporary storage and 'twice' calls for cub API
#define CUB_WRAPPER(func, ...)                                                 \
    do {                                                                       \
        size_t temp_storage_bytes = 0;                                         \
        func(nullptr, temp_storage_bytes, __VA_ARGS__);                        \
        auto &caching_allocator = *::c10::cuda::CUDACachingAllocator::get();   \
        auto temp_storage = caching_allocator.allocate(temp_storage_bytes);    \
        func(temp_storage.get(), temp_storage_bytes, __VA_ARGS__);             \
    } while (false)

//
// Convenience typedefs for CUDA types
//
using vec2 = glm::vec<2, float>;
using vec3 = glm::vec<3, float>;
using vec4 = glm::vec<4, float>;
using mat2 = glm::mat<2, 2, float>;
using mat3 = glm::mat<3, 3, float>;
using mat4 = glm::mat<4, 4, float>;
using mat3x2 = glm::mat<3, 2, float>;

//
// Legacy Camera Types
//
enum CameraModelType {
    PINHOLE = 0,
    ORTHO = 1,
    FISHEYE = 2,
    FTHETA = 3,
    LIDAR = 4,
};

#define N_THREADS_PACKED 256
#define ALPHA_THRESHOLD (1.f / 255.f)
// GAUSSIAN_EXTEND determines where the gaussian is truncated in standard deviations."
#define GAUSSIAN_EXTEND 3.33f
// MAX_ALPHA and TRANSMITTANCE_THRESHOLD are chosen so that the equivalent of
// a maximal opacity Gaussian has to be rasterized twice to reach the threshold,
// without getting the transmittance too small for numerical stability of
// the backward pass.
// i.e. TRANSMITTANCE_THRESHOLD = (1 - MAX_ALPHA)^2
#define MAX_ALPHA 0.99f
#define TRANSMITTANCE_THRESHOLD 1e-4f

#define MAX_KERNEL_DENSITY_CUTOFF 0.0113

// Floor for the antialiased compensation factor (sqrt(det_orig / det_blur)).
// Prevents compensation from reaching zero for extremely small Gaussians.
#define MIN_COMPENSATION 0.005f

// Floor for (1 - alpha) when computing 1/(1-alpha) in backward rasterization.
// Prevents gradient explosion when alpha approaches 1.0.
#define MIN_ONE_MINUS_ALPHA 1e-6f

#ifdef __HIPCC__
#   define GSPLAT_NOINLINE __noinline__
#else
#   define GSPLAT_NOINLINE
#endif

// GSPLAT_LB_256 — RDNA3+ tuned __launch_bounds__(256, 2). Also defined in
// csrc/Config.h (with the same #ifndef guard) so .hip TUs that include
// only one of the two headers still see the macro. See Config.h comment
// for the full rationale.
#ifndef GSPLAT_LB_256
#  define GSPLAT_LB_256 __launch_bounds__(256, 2)
#endif

} // namespace gsplat
