// Copyright (C) 2026 Advanced Micro Devices, Inc. All Rights Reserved.
// !!! This is a file automatically generated by hipify!!!
/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

/*
 * GSPLAT_FOR_EACH(macro, a, b, c, ...):
 *   Expands to: macro(a) macro(b) macro(c) ...
 *   - Works with zero or more arguments.
 *   - When called with no arguments, it expands to nothing.
 *   - Example:
 *       #define F(x) FEATURE_ITEM(x)
 *       GSPLAT_FOR_EACH(F, 1, 2, 3)
 *     expands to:
 *       FEATURE_ITEM(1) FEATURE_ITEM(2) FEATURE_ITEM(3)
 */

#define GSPLAT_PARENS ()

#define GSPLAT_EXPAND(...) GSPLAT_EXPAND4(GSPLAT_EXPAND4(GSPLAT_EXPAND4(GSPLAT_EXPAND4(__VA_ARGS__))))
#define GSPLAT_EXPAND4(...) GSPLAT_EXPAND3(GSPLAT_EXPAND3(GSPLAT_EXPAND3(GSPLAT_EXPAND3(__VA_ARGS__))))
#define GSPLAT_EXPAND3(...) GSPLAT_EXPAND2(GSPLAT_EXPAND2(GSPLAT_EXPAND2(GSPLAT_EXPAND2(__VA_ARGS__))))
#define GSPLAT_EXPAND2(...) GSPLAT_EXPAND1(GSPLAT_EXPAND1(GSPLAT_EXPAND1(GSPLAT_EXPAND1(__VA_ARGS__))))
#define GSPLAT_EXPAND1(...) __VA_ARGS__

#define GSPLAT_FOR_EACH(macro, ...)                                    \
  __VA_OPT__(GSPLAT_EXPAND(GSPLAT_FOR_EACH_HELPER(macro, __VA_ARGS__)))
#define GSPLAT_FOR_EACH_HELPER(macro, a1, ...)                         \
  macro(a1)                                                     \
  __VA_OPT__(GSPLAT_FOR_EACH_AGAIN GSPLAT_PARENS (macro, __VA_ARGS__))
#define GSPLAT_FOR_EACH_AGAIN() GSPLAT_FOR_EACH_HELPER

/*
 * GSPLAT_RASTERIZER_LAUNCH_BOUNDS:
 *   __launch_bounds__(256, 2) on CDNA targets (gfx940/941/942/950 — Wave64),
 *   empty on everything else.
 *
 * Why arch-gated: CDNA (Instinct) defaults give a 128 VGPR/wave cap on the
 * heavy bwd-rasterizer kernels, causing 4-7k VGPR spills per wave at high CDIM.
 * (256, 2) lifts the cap to the arch-max 256 VGPR/wave and reduces spills 33%.
 * On RDNA (wave32) the same annotation REGRESSES dispatch time by ~7% because
 * RDNA has a wider VGPR file per SIMD by default and (256, 2) over-constrains
 * occupancy. Measured on Radeon RX 7900 XTX (gfx1100) as a cross-arch control.
 * Verdict: apply only on CDNA, leave RDNA on the compiler's default sizing.
 *
 * The `__gfx*__` predefined macros are set per device-pass by amdclang++ during
 * each --offload-arch compile, so the same source produces arch-appropriate
 * code object metadata for every target in PYTORCH_ROCM_ARCH.
 */
#if defined(__gfx940__) || defined(__gfx941__) || defined(__gfx942__) || defined(__gfx950__)
  #define GSPLAT_RASTERIZER_LAUNCH_BOUNDS __launch_bounds__(256, 2)
#else
  #define GSPLAT_RASTERIZER_LAUNCH_BOUNDS
#endif
